spring.application.name=ChatbotStableChatCompletions
server.port=${PORT:8080}

# Redis Configuration
spring.data.redis.url=rediss://ommitted


# Google Cloud Project ID
google.cloud.project-id=

# Debugging
